title: Baby's First GitHub Pages Blog
author: Joshua Skootsky
email: joshua.skootsky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a simple blog for learning Jekyll

# social links
twitter_username: joshua_skootsky # DO NOT include the @ character, or else the build will fail!
github_username:  JoshuaSkootsky # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
